"""Build JSON input for 42 Đức projects in sheet Trung.
Budget 150654 KRW, Manual CPC, Max CPC = THẦU(USD) × 1500.
Exact match keyword [brand].
"""
import json

USD_TO_KRW = 1500

# Country code -> VN name (must match LOCATION_MAP in build_bulk_v2.py)
GEO = {
    'US': 'Hoa Kỳ', 'UK': 'Vương quốc Anh', 'AU': 'Úc', 'CA': 'Canada',
    'DE': 'Đức', 'FR': 'Pháp', 'IT': 'Ý', 'ES': 'Tây Ban Nha',
    'NL': 'Hà Lan', 'BE': 'Bỉ', 'AT': 'Áo', 'SE': 'Thụy Điển',
    'CH': 'Thụy Sĩ', 'FI': 'Phần Lan', 'IE': 'Ireland', 'NO': 'Na Uy',
    'DK': 'Đan Mạch', 'NZ': 'New Zealand', 'PT': 'Bồ Đào Nha',
}

def geo(codes):
    return [GEO[c] for c in codes if c in GEO]

def cpc(usd):
    return str(int(round(usd * USD_TO_KRW)))

def proj(name, link, kw, max_cpc_usd, geos, headlines, descriptions):
    return {
        "name": name,
        "campaignType": "Search",
        "link1": link,
        "adsKey": [f"[{kw}]"],
        "bidding": "Thủ công CPC",
        "budget": "150654",
        "maxCpcLimit": cpc(max_cpc_usd),
        "targetLocations": geo(geos),
        "headlines": headlines,
        "descriptions": descriptions,
    }

DATA = [
    proj("Bio Sculpture", "https://biosculpture.com/?ref=CINEPRE", "biosculpture", 1.913,
         ["UK","US","AU","CA","PT","ES"],
         ["Bio Sculpture Official","Premium Nail Gel System","Long Lasting Nail Color",
          "Hema-Free Nail Gel","Professional Nail Care","Ethical Nail Brand",
          "Biogel Salon Products","Code WELCOME10","Nail Health First","40+ Countries Trusted",
          "Shop Biogel Today","Acid-Free Nail Polish","Salon Grade Nail Gel",
          "Gemini Nail Polish","Bi-Olygel UV Acrylic"],
         ["Premium gel nail systems trusted by salons in 40+ countries. Use code WELCOME10.",
          "Hema-free, acid-free formulas that prioritize nail health and long-lasting wear.",
          "Shop Biogel, Evo, Gemini and Ethos collections. Professional quality for everyone.",
          "Ethical brand offering professional training and salon-grade products worldwide."]),

    proj("Grounding Sheet", "https://grounding-sheet.com/?ref=NGUYENDUCTRUNG&utm_source=affiliate", "grounding sheet", 2.6392,
         ["US","UK","CA","AU","IE","NZ","DE","NL","FR","BE"],
         ["Grounding Sheet Official","Earthing Bed Sheets","Better Sleep Naturally",
          "90-Night Sleep Trial","Free Shipping & Returns","French Brand 24/7",
          "Recharge With Earth","Pure Cotton Grounded","Shop Earthing Sheets",
          "Restorative Sleep Tonight","Save 50% Today","Premium Conductive Sheets",
          "Newsletter 10% Off","Shipped In 48 Hours","Earthing Mats & Sheets"],
         ["Premium grounding sheets for restorative sleep. Free shipping and 90-night trial.",
          "Recharge naturally with Earth's electrons. Save up to 50% on grounding products.",
          "Pure cotton conductive sheets shipped in 48 hours from our French warehouse.",
          "Try risk-free for 90 nights. Encrypted secure checkout with French 24/7 support."]),

    proj("Quordlepuzzles PL", "https://www.quordlepuzzles.es/?ref=CINEPRE", "quordlepuzzles", 0.28,
         ["US","AU","ES"],
         ["Quordlepuzzles Official","Wooden Animal Puzzles","Laser-Cut Precision",
          "PEFC Certified Wood","Buy 3 Get 1 Free","Free Shipping Over 49E",
          "Gift Ready Packaging","14-Day Money Back","Custom Wooden Puzzles",
          "Mandala 3D Puzzles","Up To 92% Off Sale","Premium European Timber",
          "Personalized Puzzles","Spring Sale Today","Shop Wooden Puzzles"],
         ["Premium laser-cut wooden puzzles made from PEFC certified European timber.",
          "Spring sale: buy 3 puzzles, get 1 free. Free shipping on orders over 49 euros.",
          "Gift-ready boxes with secure closure. 14-day money-back guarantee included.",
          "Custom personalized puzzles plus animal, 3D and mandala collections available."]),

    proj("Quordlepuzzles FR", "https://www.quordlepuzzles.fr/?ref=NGUYENDUCTRUNG", "quordlepuzzles fr", 0.23,
         ["US","AU","ES"],
         ["Quordlepuzzles France","Puzzles Bois Premium","Laser-Cut Precision",
          "PEFC Certified Wood","Buy 3 Get 1 Free","Free Shipping Over 49E",
          "Gift Ready Packaging","14-Day Money Back","Custom Wooden Puzzles",
          "Mandala 3D Puzzles","Up To 92% Off Sale","Premium European Timber",
          "Personalized Puzzles","Spring Sale Today","Shop Wooden Puzzles"],
         ["Premium laser-cut wooden puzzles made from PEFC certified European timber.",
          "Spring sale: buy 3 puzzles, get 1 free. Free shipping on orders over 49 euros.",
          "Gift-ready boxes with secure closure. 14-day money-back guarantee included.",
          "Custom personalized puzzles plus animal, 3D and mandala collections available."]),

    proj("Lumeo Creative", "https://lumeo-creative.com/?ref=CINEPRE&utm_source=affiliationgoaff", "lumeo creative", 0.66,
         ["FR"],
         ["Lumeo Creative Officiel","Luminaires Sur Mesure","100% Personnalisable",
          "Designs Exclusifs FR","Qualité Premium FR","Service Client Dédié",
          "Livraison Offerte","Retour Facile 14 Jours","Rendu 3D Personnalisé",
          "Suspensions Sur Mesure","Lustres Plafonniers","Appliques Murales",
          "Code CINEPRE 5%","French Craftsmanship","93% Satisfaction Client"],
         ["Luminaires français 100% personnalisables avec rendu 3D avant achat.",
          "Suspensions, lustres et lampes sur mesure. Livraison offerte temps limité.",
          "Code CINEPRE pour 5% de réduction. 93% des clients satisfaits.",
          "Designs exclusifs CRISTALI, PEARL, WOODY et SATURNE. Retour facile 14 jours."]),

    proj("Pootoo", "https://pootoo.com/?ref=CINEPRE&utm_source=affiliate%26utm_medium", "pootoo", 1.68,
         ["US","UK","CA","AU","CH"],
         ["Pootoo Official Store","Vintage Modern Furniture","Free Shipping Worldwide",
          "1095-Day Warranty","180-Day Returns","Solid Wood Construction",
          "Mid-Century Modern","Modular Storage","Up To 35% Off",
          "Coffee Tables & TVs","Bedroom Furniture","Entryway Storage",
          "Home Office Desks","Living Room Furniture","Buy Pootoo Online"],
         ["Vintage-inspired modern furniture in solid wood. Free shipping on every order.",
          "1095-day craftsmanship warranty and 180-day returns. Shop with confidence.",
          "Living, bedroom, kitchen and office solutions. Save up to 35% today.",
          "Mid-century modern designs with modular storage. Furniture with a past."]),

    proj("NEO Sabers", "https://neosabers.com/?ref=CINEPRE", "neosabers", 0.33,
         ["US","UK","DE","CA","AU","SE","ES","NO","NL","IE"],
         ["NEO Sabers Official","Premium Neopixel Sabers","Heavy Duty Dueling",
          "Infinite Color RGB","Proffie Xenopixel Tech","Replica Character Sabers",
          "Code CINEPRE 10% Off","Buy 1 Get 2 Free","Star Wars Day Sale",
          "Double Bladed Sabers","Kids Lightsabers","RGB Lightsabers",
          "SD Card Upgradeable","Free Gifts Bundle","Shop Lightsabers Now"],
         ["Premium Neopixel lightsabers with infinite color options and Proffie tech.",
          "Buy 1 Get 2 Free Star Wars Day sale. Use code CINEPRE for 10% off.",
          "Heavy duty dueling sabers with metal hilts and polycarbonate blades.",
          "Replica character designs plus RGB, kids and double-bladed lightsabers."]),

    proj("120 Life", "https://www.120life.com/?ref=CINEPRE", "120life", 0.57,
         ["US","CA","UK"],
         ["120 Life Official Store","Lower Blood Pressure","Better Numbers 2 Weeks",
          "All-Natural Ingredients","Money-Back Guarantee","Clinical Studies Backed",
          "6 Superfoods One Drink","No Medication Required","Use Code CINEPRE 15%",
          "Risk-Free BP Drink","Healthy Blood Pressure","Free BP eBook",
          "Loyalty Rewards Program","Shop Juice & Powder","Proven BP Support"],
         ["Lower your blood pressure naturally with 6 superfoods in one daily drink.",
          "Better numbers in 2 weeks or your money back. Use code CINEPRE for 15% off.",
          "All-natural BP support backed by clinical studies. No medication required.",
          "Risk-free trial with free BP guide eBook. Join the loyalty rewards program."]),

    proj("CocoBeauty", "https://cocobeauty.com/?ref=CINEPRE", "cocobeauty", 0.85,
         ["US","FR","UK","ES","DE","AU","NL","CA","IT","DK"],
         ["CocoBeauty Official","Bio-Collagen Face Masks","Reveal Natural Glow",
          "300K+ Happy Customers","Free Shipping Over $50","No Harsh Chemicals",
          "Buy 3 Get 3 Free","Code CINEPRE 10% Off","Viral Skincare Brand",
          "Anti-Aging Patches","Firming Face Creams","Calming Sheet Masks",
          "Glow Ampoules Serum","Neck & Chest Patches","Shop Skincare Today"],
         ["Reveal your skin's natural glow with scientifically proven CocoBeauty masks.",
          "Buy 3 Get 3 Free on select patches. Use code CINEPRE for 10% off.",
          "Free US shipping over $50. Trusted by 300,000+ satisfied customers.",
          "Bio-collagen masks, firming creams and glow ampoules without harsh chemicals."]),

    proj("Earasers", "https://earasers.shop/?ref=CINEPRE", "earasers", 0.54,
         ["US","AU","UK","CA","DE","NL","ES","FI","CH","AT"],
         ["Earasers Official Store","Patented V-Filter Tech","Medical-Grade Silicone",
          "Virtually Invisible Plugs","Clear Sound Not Muffled","Code CINEPRE 10% Off",
          "Award-Winning Earplugs","Music DJ Sleep Plugs","No Ear Impression Needed",
          "Free Shipping Over 39E","Comfortable Custom Fit","Be Earresponsible",
          "Hearing Protection","Motorsport Earplugs","Shop Earasers Today"],
         ["Patented V-filter earplugs that protect hearing while preserving sound clarity.",
          "Medical-grade silicone in virtually invisible design. Use code CINEPRE 10%.",
          "Music, DJ, dentist, sleep and motorsport plugs. Free shipping over 39 euros.",
          "Award-winning by MusicRadar. Comfortable custom fit without ear impression."]),

    proj("Tecknet", "https://tecknet.co.uk/?ref=CINEPRE", "tecknet", 0.34,
         ["US","UK","DE","FR","ES","IT","CA","NL","AT","BE"],
         ["Tecknet Official Store","Quality Tech Accessories","Wireless Mouse Keyboard",
          "Bluetooth Headphones","Premium Power Banks","Code CINEPRE 10% Off",
          "Free UK Shipping","2-Year Warranty Included","Computer Accessories",
          "Gaming Peripherals","Mobile Accessories","Smart Home Devices",
          "Buy Tecknet Online","Trusted Tech Brand","Fast Tracked Delivery"],
         ["Quality tech accessories at fair prices. Use code CINEPRE for 10% off.",
          "Wireless mice, keyboards, headphones, power banks and gaming peripherals.",
          "2-year warranty included. Free UK shipping with fast tracked delivery.",
          "Trusted by thousands across Europe and North America. Shop Tecknet today."]),

    proj("Engwe DE", "https://de.engwe.com/?ref=CINEPRE", "engwe", 1.35,
         ["UK","DE","IT","US","ES","NL","DK","PT","SE","AT"],
         ["Engwe Official Store DE","Fun Riding E-Bikes","Up To 1300E Discount",
          "Code CINEPRE 100 Euro","EU Road-Legal E-Bikes","Torque Sensor Models",
          "350km Extended Range","Foldable City E-Bikes","Fat Tire E-Bikes",
          "Cargo & Commuter Bikes","1-2 Year Warranty","Free EU Shipping",
          "Klarna PayPal Pay Later","Lifetime Support","Shop Engwe Bikes"],
         ["Fun riding with Engwe e-bikes. Save up to 1300 euros on city models.",
          "Use code CINEPRE for 100 euros off. EU road-legal e-bikes with 1-2 year warranty.",
          "Foldable, fat tire, cargo and commuter e-bikes plus Y-series e-scooters.",
          "Up to 350km range with torque sensors. Pay later with Klarna or PayPal."]),

    proj("Gear Geek", "https://geargeek.co.uk/?ref=CINEPRE", "geargeek", 1.583,
         ["CA","US","UK","FI","FR","AU"],
         ["Gear Geek Online Store","Tech Gear & Accessories","Premium Quality Gear",
          "Free UK Shipping","Trusted Online Store","Secure Online Checkout",
          "Code CINEPRE Save More","Computer Accessories","Mobile Phone Gear",
          "Smart Home Devices","Audio Headphones","Fast Order Dispatch",
          "Buy Gear Geek Online","Shop Tech Today","Top Rated UK Store"],
         ["Premium tech gear and accessories. Free UK shipping with fast dispatch.",
          "Use code CINEPRE to save on your order. Secure online checkout guaranteed.",
          "Computer, mobile, smart home and audio accessories all in one place.",
          "Trusted UK online store with top customer ratings. Shop Gear Geek today."]),

    proj("Merino Tech", "https://merino.tech/?ref=slssmgxa", "merino tech", 0.32,
         ["US","FR","ES","UK","DE","AU","IT","CA","BE","NL"],
         ["Merino Tech Official","100% Pure Merino Wool","Natural Odor Resistance",
          "All-Season Temp Control","Ultra Soft Non-Itching","Free Shipping Over $49",
          "New Zealand Wool Source","Code MEMORIALDAY 20%","Base Layer Sets",
          "Hoodies T-Shirts Tops","Premium Quality Pricing","Kids Merino Collection",
          "Buy Merino Online","Shop Base Layers","Newsletter 20% Off"],
         ["Premium 100% pure New Zealand merino wool apparel with natural odor resistance.",
          "Use code MEMORIALDAY for 20% off sitewide. Free shipping on orders over $49.99.",
          "Naturally breathable and made for movement. Adapts across every season.",
          "Base layer sets, hoodies, t-shirts, pants and kids collections available."]),

    proj("Smitizen", "https://www.smitizen.com/?ref=calixto", "smitizen", 1.39,
         ["US","ES","DE","UK","FR","CA","NL","IT","AU","CH"],
         ["Smitizen Official Store","Premium Silicone Gear","15+ Years Experience",
          "Custom Personalization","Discreet Shipping","Realistic Transformation",
          "Expert Craftsmanship","Safe Inclusive Brand","20-50% Off Sale",
          "Mystery Box Event","Free Shipping Items","Silicone Muscle Suits",
          "Custom Made Hoods","Bundle & Save Deals","Buy Smitizen Online"],
         ["Premier silicone fetish gear from a trusted brand with 15+ years of experience.",
          "Custom personalization plus 20-50% off select items. Mystery box event active.",
          "Premium-grade silicone with discreet, confidential shipping protecting privacy.",
          "Bundle deals plus free shipping on select items. Safe and inclusive community."]),

    proj("Sofabaton", "https://www.sofabaton.com/?ref=ymefdwhx", "sofabaton", 6.257,
         ["US","DE","CA","UK","NL","AU","FR","CH","AT","BE"],
         ["Sofabaton Official Store","One Remote All Devices","Universal Remote Control",
          "Activity-Based Automation","Wide Device Support","Intuitive Touchscreen",
          "Premium Build Quality","360 IR Hub Coverage","Easy App Setup",
          "X2 Premium Remote","X1S Everyday Remote","U3 All-In-One Control",
          "Charging Dock Included","Shop Universal Remotes","Buy Sofabaton Today"],
         ["One smart remote controls all your devices. Activity-based automation built in.",
          "Premium build with intuitive touchscreen and 360-degree IR hub coverage.",
          "X2, X1S and U3 universal remotes. Compatible with most major device brands.",
          "Easy app-based setup. Premium build quality eliminates multi-remote clutter."]),

    proj("Jean Marc Joubert", "https://jeanmarcjoubert.com/?ref=rtpilfhc", "jeanmarcjoubert", 1.45,
         ["FR"],
         ["Jean Marc Joubert FR","Expert Soin Cheveux","2000+ Produits Capillaires",
          "50+ Marques Partenaires","Conseil Pro Coiffeur","Livraison Rapide France",
          "Paiement 4x Sécurisé","Programme Fidélité","Jusqu'a 47% De Réduction",
          "Shampoings Pro","Sérums Soins","Compléments Cheveux",
          "Matériel Coiffure","Esthétique Pro","Boutique Officielle"],
         ["Expert français en soin capillaire avec plus de 2000 produits professionnels.",
          "Conseils personnalisés de coiffeurs experts. Programme fidélité disponible.",
          "Paiement en 4 fois sécurisé. Livraison rapide partout en France.",
          "Jusqu'à 47% de réduction sur articles sélectionnés. Boutique officielle."]),

    proj("Stay Another Day", "https://stayanotherday.com/?ref=vohmpphk", "stayanotherday", 0.04,
         ["US"],
         ["Stay Another Day Apparel","Mental Health Matters","Code LOVEMORE 20% Off",
          "988 Lifeline Donation","Female-Owned Brand","Hidden 988 Designs",
          "Embroidered Apparel","Hoodies Crewnecks Tees","Bulk Team Orders",
          "Kids Youth Apparel","Hats Cups Accessories","Conversation Starters",
          "Shop With Purpose","Be A Light","Buy Stay Another Day"],
         ["Mental health awareness apparel. Use code LOVEMORE for 20% off site wide.",
          "A portion of every sale donated to the 988 Suicide and Crisis Lifeline.",
          "Embroidered hoodies, crewnecks, tees, hats and accessories with hidden meaning.",
          "Female-owned small business with bulk team ordering for organizations."]),

    proj("Wall of Fame", "https://walloffame.fr/?ref=ohnyztxt", "walloffame", 0.58,
         ["US","FR"],
         ["Wall of Fame Officiel","Affiches Sport Premium","Illustrées Main France",
          "Papier 250g Matte","Giclée Print Quality","Expédition 24-48h",
          "Code HELLO10 -10%","Personnalisation Dispo","Football Basket Rugby",
          "Tennis Golf Cyclisme","Affiches Marathon","T-Shirts Sport",
          "Mugs Sport Collection","Qualité Musée","Boutique Fans Sport"],
         ["La boutique des fans de sport. Affiches illustrées à la main en France.",
          "Qualité premium digne des musées. Papier matte 250g/m² avec impression giclée.",
          "Code HELLO10 pour 10% de réduction sur première commande. Livraison 3-4 jours.",
          "Football, basket, rugby, tennis et plus. Posters personnalisables disponibles."]),

    proj("Haylou", "https://haylou.com/?ref=wwsevxdy", "haylou", 0.17,
         ["US","ES","FR","DE","UK","IT","CA","NL","AU","SE"],
         ["Haylou Official Store","Power In Self","Noise Reduction -54dB",
          "9.8mm Slim Earbuds","LDAC Hi-Res Audio","40 Hour Battery Life",
          "Titanium Drivers","30 Day Returns","Lifetime Support",
          "Free Ship Over $69","Flowbuds N55 ANC","Solar Lite 2 Watch",
          "S40 ANC Headphones","18-Day Smartwatch","Shop Haylou Today"],
         ["Premium audio with -54dB noise reduction and LDAC hi-res sound technology.",
          "9.8mm slim earbuds with 40-hour battery and titanium-coated drivers.",
          "Smartwatches with 18-day battery life and GPS tracking. 30-day returns.",
          "Free shipping over $69. Lifetime customer support included with every order."]),

    proj("Support Plante", "https://support-plante.com/?ref=iwiglqag", "support plante", 0.73,
         ["FR","CA"],
         ["Support Plante No 1 FR","Décoration Végétale","Livraison Gratuite FR",
          "Garantie Satisfait 14j","4.6/5 De 650+ Avis","Porte Plante Design",
          "Étagère Plante Bois","Suspension Macramé","Pots Sur Roulettes",
          "Treillis Plante Grimp","Réduction 15% Hebdo","Guide Plante Offert",
          "Bambou Rotin Métal","Livraison 24-48h","Shop Décoration Plante"],
         ["La référence n°1 en France en décoration végétale. Livraison gratuite.",
          "Porte plante, étagère, suspension et treillis en bois, métal ou rotin.",
          "Garantie satisfait ou remboursé 14 jours. Guide plante offert valeur 22.90 euros.",
          "Réduction 15% chaque semaine. Note 4.6/5 par plus de 650 clients satisfaits."]),

    proj("Nsabers IT", "https://nsabers.it/?ref=hliisxpj", "nsabers", 1.0817,
         ["US","DE","UK","AU","ES","CA","IT","SE","DK","CH"],
         ["Nsabers IT Officiale","Spade Laser Premium","Effetto Luce Finale",
          "12+ Colori LED RGB","Custodia Alluminio","Lame Policarbonato",
          "Code MAY4 -15% Off","Garanzia 1 Anno","Effetti Flash-on-Clash",
          "Spada ECO Cavaliere","Maestro Premium Spada","Free Spada Da 299E",
          "Fino A 50% Sconto","Accessori Spade","Buy Nsabers Today"],
         ["Spade laser premium con effetti luminosi e sonori spettacolari.",
          "Codice MAY4 per 15% di sconto. Spada gratis con acquisti da 299 euro.",
          "Custodie alluminio anodizzato e lame in policarbonato resistente.",
          "Garanzia 1 anno e supporto 24/7. Soddisfatto o rimborsato in 15 giorni."]),

    proj("Quordlepuzzles COM", "https://www.quordlepuzzles.com/?ref=scsatyln", "quordlepuzzles com", 0.12,
         ["US","AU","ES"],
         ["Quordlepuzzles Official","Wooden Animal Puzzles","Laser-Cut Precision",
          "PEFC Certified Wood","Buy 3 Get 1 Free","Free Shipping Over $49",
          "Gift Ready Packaging","14-Day Money Back","Custom Wooden Puzzles",
          "Mandala 3D Puzzles","Up To 92% Off Sale","Premium European Timber",
          "Personalized Puzzles","Spring Sale Today","Shop Wooden Puzzles"],
         ["Premium laser-cut wooden puzzles made from PEFC certified European timber.",
          "Spring sale: buy 3 puzzles, get 1 free. Free shipping on orders over $49.",
          "Gift-ready boxes with secure closure. 14-day money-back guarantee included.",
          "Custom personalized puzzles plus animal, 3D and mandala collections available."]),

    proj("Tribit", "https://www.tribit.com/?ref=sxqmkawk", "tribit", 0.64,
         ["US","DE","UK","FR","CA","IT","ES","AU","PT","CH"],
         ["Tribit Official Store","Sound That Matters","XBass Bass Enhancement",
          "Audiodo Hearing Tech","30-Day Money Back","Lifetime Support",
          "Free Ship Over $99","Newsletter 10% Off","$5 Off Orders $150+",
          "$10 Off Orders $200+","StormBox Speakers","FlyBuds True Wireless",
          "Portable Bluetooth","Premium Audio Brand","Shop Tribit Today"],
         ["Sound that matters. Premium audio with XBass enhancement and Audiodo tech.",
          "StormBox portable speakers and FlyBuds true wireless earbuds available now.",
          "Free shipping over $99. Get $5 off orders $150+ or $10 off orders $200+.",
          "30-day money back guarantee and lifetime customer support included."]),

    proj("Eleglide", "https://eleglide.com/?ref=tybzepow", "eleglide", 0.15,
         ["DE","FR","IT","UK","ES","NL","BE","SE","DK","CH"],
         ["Eleglide Official Store","Lead The Way Forward","High Quality E-Bikes",
          "Up To 150km Range","Hydraulic Disc Brakes","3-Year Warranty",
          "Free Shipping Over 39E","EU Compliant Bikes","96% Satisfaction",
          "Mountain City E-Bikes","Step-Through E-Bikes","9.6M Tons CO2 Saved",
          "Affordable Premium","Buy Eleglide Online","Shop E-Bikes Today"],
         ["Lead the way forward with high quality e-bikes at affordable prices.",
          "Up to 150km range with hydraulic disc brakes. 3-year warranty available.",
          "EU-compliant mountain, city, tour and step-through e-bikes plus accessories.",
          "Free shipping over 39 euros. 96% customer satisfaction across Europe."]),

    proj("Dasaita", "https://www.dasaita.com/?ref=oocdrema", "dasaita", 2.27,
         ["US","IT","CA","ES","DE","FR","UK","AU","SE","AT"],
         ["Dasaita Official Store","Android Car Stereo","Ultimate Dashboard Upgrade",
          "Plug & Play Guarantee","OEM Look Integration","Keep Factory Features",
          "QLED + DTS Audio","Qualcomm 665 Processor","Wireless CarPlay",
          "Wireless Android Auto","1-Year Warranty US","Save $150-$240",
          "Toyota Honda Stereos","Free US Shipping","Buy Dasaita Today"],
         ["The ultimate Android car stereo upgrade. Plug & play guarantee included.",
          "QLED display with DTS audio and Qualcomm 665 processor. Save $150-$240.",
          "Wireless CarPlay and Android Auto. Keep factory backup camera and controls.",
          "Custom-fit dash kits for Toyota, Honda and more. 1-year warranty with US support."]),

    proj("Morfeo", "https://morfeo.com/?ref=dusqrlqm", "morfeo", 1.4344,
         ["IT","ES","US","BE","FR","CA","DE","UK","NL","AU"],
         ["Morfeo Official Store","Sleep More Sleep Better","100-Night Trial Free",
          "10-Year Warranty","Free Shipping Returns","Direct From Factory",
          "Premium Certified Cotton","50% Off Mattresses","Colchón Nature 1065E",
          "Colchón Altus 699E","VisCool Memory Foam","Original Hybrid Mattress",
          "Pressure Relief Bed","Buy Morfeo Mattress","Shop Bedding Today"],
         ["El mejor colchón para dormir más y mejor. 100 noches de prueba gratis.",
          "Garantía 10 años, envío y devolución gratis. Fabricación directa de fábrica.",
          "50% de descuento en colchones Nature, Altus, VisCool e Original Hybrid.",
          "Alivio de presión con materiales certificados de algodón premium."]),

    proj("ODODOS", "https://ododos.co/?ref=NGUYENDUCTRUNG", "ododos", 0.32,
         ["US","DE","CA","UK","ES","AU","IE"],
         ["ODODOS Official Store","Only Here Only Faster","Yoga Workout Leggings",
          "Premium Activewear","odSTRATUM Fabric","ODLEX ODCLOUD Tech",
          "ODLIFT Compression","Buy 3+ 15% Off","Code 2026S15",
          "Full Length Leggings","7/8 Length Capris","Tanks Hoodies Jackets",
          "Yoga Tennis Fitness","Activity-Specific Wear","Shop Activewear"],
         ["Only here, only faster. Premium activewear with proprietary fabric technology.",
          "Buy 3+ items get 15% off with code 2026S15. Fast shipping included.",
          "Specialized odSTRATUM, ODLEX, ODCLOUD and ODLIFT fabric technologies.",
          "Leggings, tops, bottoms for yoga, fitness, tennis and casual everyday wear."]),

    proj("ThankGod", "https://thankgod.com/?ref=kfncpljg", "thankgod", 0.30,
         ["US","CA"],
         ["ThankGod Official Store","Be A Light","Christian Clothing Brand",
          "Faith-Based Apparel","Oversized Vintage Tees","Statement With Purpose",
          "Code MEMORIAL30 30%","Quality Christian Wear","Embossed Embroidered",
          "Hoodies T-Shirts","Wristbands Socks","Gift Cards Available",
          "Drop Alert Club","Exodus Cry Partner","Shop Faith Apparel"],
         ["Be a light to those around you with quality Christian streetwear and apparel.",
          "Memorial Day sale: use code MEMORIAL30 for 30% off. Faith-driven messaging.",
          "Oversized vintage tees, hoodies, wristbands and accessories from $7 to $70.",
          "Partnership with Exodus Cry for social impact. Drop alert club included."]),

    proj("ACMEJOY", "https://www.acmejoy.nl/?ref=lgmtleod&utm_medium=Goaffpro%26utm_campaign", "acmejoy", 1.17,
         ["US","FR","DE","IT","NL","BE","UK","AU","AT","SE"],
         ["ACMEJOY Official Store","Discreet No Logo Packaging","90-Day Returns",
          "Free Shipping Over 49E","100% Buyer Protection","Wide Selection",
          "Up To 50% Off Sale","Flash Sales Daily","Premium Quality Products",
          "Klarna Pay Later","Multiple Payments","Discrete Tracking",
          "Quality & Function","Shop ACMEJOY Today","Buy Adult Toys Online"],
         ["100% peace of mind shopping. No ACMEJOY logo on your discreet packaging.",
          "90-day return guarantee plus free shipping on orders over 49 euros.",
          "Up to 50% off select items with flash sales daily. Klarna pay later available.",
          "Premium quality with full buyer protection. Discrete logistics tracking."]),

    proj("Europesnus", "https://europesnus.com/?ref=ofwjdlpn", "europesnus", 0.06,
         ["FI","NL","DE","BE","IT","SE","US","CH","DK","UK"],
         ["Europesnus Official Store","Best Snus Prices","Same-Day Shipping",
          "Order By 2PM Ships","3-5 Day Delivery","Free Gift Cans",
          "Wide Snus Selection","Tobacco-Free Pouches","Caffeine Pouches",
          "Disposable Vapes","Cuba 20% Off","Nois 50% Off",
          "Garant Prime 25% Off","Edel 20% Off","Buy Snus Online"],
         ["Best prices on snus worldwide. Same-day shipping when ordered by 2 PM.",
          "3-5 day delivery guarantee with secure payment methods and free gift cans.",
          "Cuba 20% off, Nois 50% off, Garant Prime 25% off, Edel 20% off till May 24.",
          "Nicotine pouches, caffeine pouches and disposable vapes all in one store."]),

    proj("Tuneful Hair", "https://www.tunefulhair.com/?ref=tkzzsbnx", "tunefulhair", 1.21,
         ["US","CA","SE"],
         ["Tuneful Hair Official","100% Real Human Hair","HD Transparent Lace",
          "Pre-Plucked Pre-Cut","Free Shipping 30 Day Returns","Multiple Textures Colors",
          "Professional Toning","Glueless Wear-Go","Pay Later Available",
          "13x6 Lace Front Wigs","360 Lace Wigs","Bob Curly Body Wave",
          "Up To 47% Off Sale","BOGO Flash Sales","Buy Wigs Online"],
         ["100% real human hair wigs with HD transparent lace technology.",
          "Pre-plucked and pre-cut ready-to-wear designs. Free shipping and 30-day returns.",
          "Up to 47% off plus flash and BOGO deals. Pay later options available.",
          "13x6 lace front, 360 lace and HD lace wigs in multiple textures and colors."]),

    proj("Caravan Bits Bobs", "https://cbbs.net.au/?ref=kpcmjrgi", "caravanbits", 0.04,
         ["UK","US","AU","CA","FR","NL","NZ"],
         ["Caravan Bits & Bobs AU","Closing Down Sale","Up To 66% Off",
          "Quality Caravan Gear","Camping Outdoor Gear","Heavy Duty Wheel Chocks",
          "Food Grade Water Hoses","Collapsible Camp Gear","Padded Storage Bags",
          "Trusted eBay Seller","BBQ Outdoor Gear","Safety Tie-Downs",
          "Buy Now Save Big","Limited Stock Sale","Shop Closing Down"],
         ["Caravan, camping and outdoor gear for easier getaways. Up to 66% off closing sale.",
          "Quality lined storage bags, heavy duty wheel chocks and food grade water hoses.",
          "Collapsible camping gear and comprehensive caravan setup solutions.",
          "Trusted seller with high eBay ratings. Limited stock at clearance prices."]),

    proj("Military Shop", "https://militaryshop.com.au/?ref=NGUYENDUCTRUNG", "militaryshop", 0.32,
         ["AU","DE","CH","SE"],
         ["Military Shop Australia","Authentic Licensed Gear","$1M+ Donated Veterans",
          "Quality Guaranteed","Fast Shipping Returns","30 Years Experience",
          "4.8 Star Reviews","Mayday Sale Active","Ceremonial Swords",
          "Military Medals Mounting","Tactical Boots Gear","Field Gear Packs",
          "Army Navy Air Force","BrandNet Rewards","Shop Military Today"],
         ["Australia's leading military store trusted by ADF, RAN, RAAF and RSL.",
          "Authentic licensed products with $1M+ donated to veteran causes.",
          "Ceremonial swords, medals, mounting, tactical boots and field gear.",
          "Mayday sale active. 30 years industry experience with 4.8 star rating."]),

    proj("Renpho AU", "https://renpho.au/?ref=trjwbctj", "renpho", 0.39,
         ["US","UK","DE","CA","AU","FR","ES","IT","NL","AT"],
         ["Renpho AU Official","Empower Your Wellness","15M+ Users Worldwide",
          "Smart Body Composition","AI Health Insights","Family Health Devices",
          "Code MOM26 12% Off","Mother's Day Sale","Smart Scales No.1",
          "Massage Guns Eye Foot","LED Beauty Masks","Smart Jump Ropes",
          "Air Purifiers Heating","Track Body Not Weight","Buy Renpho Today"],
         ["Empower your wellness. Track your body, not just your weight with smart scales.",
          "Mother's Day sale: use code MOM26 for extra 12% off. 15M+ users worldwide.",
          "AI-powered health insights with body composition scanners and smart rings.",
          "Massage guns, LED beauty masks, smart jump ropes and air purifiers."]),

    proj("KAT VR", "https://www.kat-vr.com/?ref=pkxaslxs", "katvr", 0.03,
         ["US","UK","DE","FR","IT","AU","ES","AT","BE","IE"],
         ["KAT VR Official Store","Break Physical Limits","360 Natural Movement",
          "1:1 Locomotion Control","Haptic Feedback Built-In","VR Fitness Gamification",
          "3000+ Games Supported","Reduces Motion Sickness","Bundle 40% Off",
          "$599 Steam Card Free","KAT Walk C2 Plus","C2 Core Treadmill",
          "Loco S Motion Sensors","Walk Mini S Pro","Shop VR Treadmills"],
         ["Break physical boundaries. 360-degree natural movement with 1:1 locomotion.",
          "Bundle 40% off includes KAT Shoes, Nexus and free $599 Steam gift card.",
          "Supports 3000+ games on SteamVR and Meta Quest. Reduces motion sickness.",
          "Real-time health tracking with heart rate, steps and calorie monitoring."]),

    proj("Steezy", "https://steezy.com/?ref=cljcgvlx", "steezy", 0.65,
         ["US","UK","AU","CA","DE","FR","NL","ES","IT","FI"],
         ["Steezy Official Store","Action Sports Apparel","Snowboard Surf Skate",
          "Free US Ship Over $100","Embroidered Graphic Tees","Snapbacks Beanies Hats",
          "Mens Womens Kids","Size-Inclusive Designs","Save 30-50% Sale",
          "BMX Wakeboard Motox","Hoodies Sweatshirts","Long Sleeves Tanks",
          "Vinyl Stickers Gaiters","Reigning Streetwear","Buy Steezy Online"],
         ["Action sports inspired lifestyle wear for snow, surf and skate communities.",
          "Free US shipping over $100. Save 30-50% on hoodies, tees and accessories.",
          "Snapbacks, trucker hats, beanies plus apparel for men, women and kids.",
          "Reigning supreme in action-sports streetwear. Email signup for early access."]),

    proj("Intense Oud", "https://www.intenseoud.com/?ref=dcjmhfvk", "intenseoud", 0.70,
         ["US","SE"],
         ["Intense Oud Official","Fragrance Reimagined","Free US Shipping",
          "500K+ Positive Reviews","8+ Years In Business","Premium Arabian Oud",
          "10000+ Products","Serves 115+ Countries","Intense Rewards Program",
          "Niche Perfumes Selection","Oils Bakhoor Diffusers","Body Care Mists",
          "Gift Sets 3-Piece","Couples Bundles","Buy Oud Online"],
         ["Fragrance reimagined as an experience. Premium Arabian and niche perfumes.",
          "500K+ positive reviews across 115+ countries. 8+ years in fragrance business.",
          "10,000+ products including perfumes, oils, bakhoor, diffusers and body care.",
          "Free US shipping with Intense Rewards loyalty program. Expert support included."]),

    proj("Procolored", "https://www.procolored.com/?ref=NGUYENDUCTRUNG&utm_campaign=NGUYEN%20DUC%20TRUNG&utm_medium=affiliate&utm_source=goaffpro", "procolored", 1.2001,
         ["US","FR","UK","DE","CA","IT","AU","BE","AT","NO"],
         ["Procolored Official","DTF Printer Technology","UV DTF Printing",
          "UV Flatbed Printers","Multi-Format Options","Professional Grade",
          "Commercial Print Systems","Digital Textile Print","Flatbed Versatility",
          "Specialty UV Capable","Print Any Material","Custom Print Solutions",
          "Shop DTF Printers","Buy UV Printers","Procolored Direct"],
         ["Advanced DTF printer technology and UV flatbed printing solutions.",
          "Multi-format options including DTF, UV DTF and UV flatbed printers.",
          "Professional-grade equipment for commercial and digital textile printing.",
          "Specialty UV printing capabilities for printing on virtually any material."]),

    proj("Play Planet", "https://playplanet.us/?ref=vkdshhvv", "playplanet", 0.25,
         ["US","ES","UK","PT","AU"],
         ["Play Planet Official","Imagination Runs Free","Eco-Friendly Toys",
          "Non-Toxic Sustainable","Montessori Waldorf Toys","Women-Owned Small Biz",
          "Naturally Sourced","Hypoallergenic Toys","Newsletter 10% Off",
          "Free Ship Over $150","$8 Flat Rate Ship","Felt Wooden Puzzles",
          "Pretend Play Kitchens","Baby Sensory Toys","Buy Eco Toys"],
         ["Where imagination runs free. Eco-friendly, non-toxic, sustainable handmade toys.",
          "Montessori and Waldorf inspired. Naturally sourced and hypoallergenic materials.",
          "Free US shipping over $150 or $8 flat rate. Newsletter 10% off available.",
          "Felt toys, wooden puzzles, play kitchens, baby toys and educational play sets."]),

    proj("Nurse In The Making", "https://anurseinthemaking.com/?ref=nimyeamd", "nurseinthemaking", 0.11,
         ["US","DE","IT"],
         ["Nurse In The Making","Nursing School No Fluff","300K+ Students Helped",
          "Memory Tricks Mnemonics","Created By Nurses","Free US Shipping",
          "Bundle Save Up 20%","Illustrated Study Notes","Comparison Charts",
          "Pharmacology Flashcards","Med-Surg Study Guide","NCLEX Prep Materials",
          "Clinical Pocket Guides","Digital eBooks","Buy Study Guides"],
         ["Nursing school without the fluff. Trusted by 300,000+ students helped.",
          "Bundle and save up to 20% off. Created by nurses with memory tricks and mnemonics.",
          "Free US shipping on flashcards, study guides, NCLEX prep and clinical references.",
          "Visual learning with illustrations, comparison charts and digital eBooks."]),

    proj("Au Vodka", "https://auvodka.co.uk/?ref=urlknqmy", "auvodka", 0.12,
         ["UK","US","NL","ES","FR","BE","DK","CA"],
         ["Au Vodka Official UK","One Sip & You Know","Five-Times Distilled",
          "British Ultra Premium","11 Unique Flavours","Pre-Mixed Cans Available",
          "Personalisation Option","Gold Gang Rewards","Au x Tango Edition",
          "Miami Mango Limited","Mixed 24-Pack £5 Off","Gift Sets Available",
          "Glassware Barware","Celebrity Endorsed","Buy Au Vodka Online"],
         ["British ultra-premium vodka. One sip and you'll know - Au've been Tango'd.",
          "Five-times distilled smooth vodka in 11 unique flavours plus ready-to-drink cans.",
          "Au Vodka x Tango collaboration and Miami Mango limited edition available now.",
          "Mixed 24-pack with £5 savings. Join the Gold Gang loyalty rewards programme."]),
]

if __name__ == '__main__':
    out = 'trung_duc_input.json'
    with open(out, 'w', encoding='utf-8') as f:
        json.dump(DATA, f, ensure_ascii=False, indent=2)
    print(f"Wrote {len(DATA)} projects to {out}")
    for i, p in enumerate(DATA, 1):
        h_max = max(len(h) for h in p['headlines'])
        d_max = max(len(d) for d in p['descriptions'])
        flag = ' !H' if h_max > 30 else ''
        flag += ' !D' if d_max > 90 else ''
        print(f"  {i:2d}. {p['name']:25s} maxCpc={p['maxCpcLimit']:>5s} geo={len(p['targetLocations']):2d} hMax={h_max} dMax={d_max}{flag}")
